name: Main CI/CD
on:
  repository_dispatch:
    types: [module-updated]
  push:
    branches:
      - main
      - uat
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Main Repository
        uses: actions/checkout@v4
      - name: Deploy to CI/CD Server
        run: |
          # Set up SSH key
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 172.105.105.144 >> ~/.ssh/known_hosts
          # Deploy to server
          # if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            rsync -avz --exclude '.git' . root@172.105.105.144:/root/repo/demo_master_repository_for_CICD
            ssh root@172.105.105.144 'cd /root/repo/demo_master_repository_for_CICD && git pull origin main'
          # else
            # rsync -avz --exclude '.git' . user@ci-cd-server:/path/to/app
            # ssh user@ci-cd-server 'cd /path/to/app && git pull origin uat && composer install --no-dev'
          # fi
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
      - name: Checkout Test Repository
        uses: actions/checkout@v4
        with:
          repository: yiptsunho/fiyge_test_api
          token: ${{ secrets.TEST_REPO_TOKEN }}
          path: test-repo
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install Test Dependencies
        run: |
          cd test-repo
          npm install
      - name: Run API Tests
        id: api-tests
        run: |
          cd test-repo
          npm test index -- --json > ../test-results.json
        env:
          API_URL: ${{ github.ref == 'refs/heads/main' && 'http://prod-server:8080' || 'http://ci-cd-server:8080' }}
      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results.json
          retention-days: 7
      - name: Debug MODULE_REPO_TOKEN
        if: always()
        run: |
          echo "MODULE_REPO_TOKEN is set: ${{ secrets.MODULE_REPO_TOKEN != '' }}"
      - name: Debug Client Payload
        if: always()
        run: |
          echo '{
            "test_status": "${{ job.status }}",
            "results_url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}",
            "commit": "${{ github.event.client-payload.commit || github.sha }}",
            "module": "demo_module_repository_for_CICD",
            "module_repo_token": "${{ secrets.MODULE_REPO_TOKEN }}"
          }'
      - name: Notify Module Repository
        if: always()
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.MODULE_REPO_TOKEN }}
          repository: yiptsunho/demo_module_repository_for_CICD
          event-type: test-results
          client-payload: |-
            {
              "test_status": "${{ job.status }}",
              "results_url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}",
              "commit": "${{ github.event.client-payload.commit || github.sha }}",
              "module": "demo_module_repository_for_CICD",
              "module_repo_token": "${{ secrets.MODULE_REPO_TOKEN }}"
            }
