name: Main CI/CD
on:
  repository_dispatch:
    types: [module-updated]
  push:
    branches:
      - main
      - uat
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: mbstring, curl, pdo_mysql
      - name: Install Module Dependencies
        run: echo "Install module dependencies script placeholder"
      # - name: Install Main Dependencies
      #   run: composer install
      - name: Build Application
        run: echo "Build application script placeholder"
      - name: Deploy to CI/CD Server
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "Deploy to production"
          else
            echo "Deploy to UAT"
          fi
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install Test Dependencies
        run: npm install
      - name: Run API Tests
        id: api-tests
        run: |
          npm test index -- --json > test-results.json
        env:
          API_URL: ${{ github.ref == 'refs/heads/main' && 'http://prod-server:8080' || 'http://ci-cd-server:8080' }}
      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results.json
          retention-days: 7
      - name: Notify Module Repository
        if: always()
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.MODULE_REPO_TOKEN }}
          repository: your-org/${{ github.event.client-payload.module }}
          event-type: test-results
          client-payload: |
            {
              "test_status": "${{ job.status }}",
              "results_url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}",
              "commit": "${{ github.event.client-payload.commit }}",
              "module": "${{ github.event.client-payload.module }}"
            }
